export const CAO_PARTICULIERE_BEVEILIGING_KEY = "cao_particuliere_beveiliging";

export const PB_FULLTIME_STANDARD_TEMPLATE_ID = "pb_fulltime_standard_v1";

export const PB_CAO_FUNCTION_GROUP_OPTIONS = [
  { value: "objectbeveiliger_receptionist", label: "Objectbeveiliger / receptionist" },
  { value: "mobiel_surveillant", label: "Mobiel surveillant" },
  { value: "winkelsurveillant", label: "Winkelsurveillant" },
  { value: "brandwacht", label: "Brandwacht" },
  { value: "geld_waardetransporteur", label: "Geld- en waardetransporteur" },
  { value: "centralist", label: "Centralist" },
  { value: "non_security_staff", label: "Niet-operationele functie" },
];

export const PB_CAO_FUNCTION_LEVEL_OPTIONS = [
  { value: "aspirant", label: "Aspirant" },
  { value: "a", label: "Functie A" },
  { value: "b", label: "Functie B" },
  { value: "c", label: "Functie C" },
  { value: "d", label: "Functie D" },
  { value: "e", label: "Functie E" },
  { value: "leidinggevend", label: "Afwijkend leidinggevend (controleren)" },
  { value: "not_applicable", label: "Niet van toepassing" },
];

const PB_SALARY_SCALE_BY_FUNCTION_LEVEL = {
  aspirant: 2,
  a: 3,
  b: 4,
  c: 5,
  d: 6,
  e: 7,
};

export function pbSalaryScaleForFunctionLevel(functionLevel) {
  return PB_SALARY_SCALE_BY_FUNCTION_LEVEL[functionLevel] || null;
}

const PB_FUNCTION_GROUP_BY_FUNCTION = {
  objectbeveiliger: "objectbeveiliger_receptionist",
  receptionist: "objectbeveiliger_receptionist",
  receptie: "objectbeveiliger_receptionist",
  surveillant: "objectbeveiliger_receptionist",
  bedrijfssurveillant: "objectbeveiliger_receptionist",
  mobiel_surveillant: "mobiel_surveillant",
  alarmopvolging: "mobiel_surveillant",
  winkelsurveillant: "winkelsurveillant",
  brandwacht: "brandwacht",
  geld_waardetransporteur: "geld_waardetransporteur",
  waardetransport_chauffeur: "geld_waardetransporteur",
  waardetransport_bijrijder: "geld_waardetransporteur",
  centralist: "centralist",
  centralist_pac: "centralist",
  centralist_vtc: "centralist",
  videosurveillant: "centralist",
  toezichthouder: "centralist",
  evenementenbeveiliger: "objectbeveiliger_receptionist",
  horecabeveiliger: "objectbeveiliger_receptionist",
  host: "non_security_staff",
  binnendienst: "non_security_staff",
  planner: "non_security_staff",
  roostermaker: "non_security_staff",
  operationeel_coordinator: "non_security_staff",
  operationeel_manager: "non_security_staff",
  administratief_medewerker: "non_security_staff",
  financieel_administratief: "non_security_staff",
  salarisadministrateur: "non_security_staff",
  hr_medewerker: "non_security_staff",
  hr_manager: "non_security_staff",
  accountmanager: "non_security_staff",
  sales_manager: "non_security_staff",
  kwaliteitsmanager: "non_security_staff",
  compliance_manager: "non_security_staff",
  directie: "non_security_staff",
};

export function suggestPbCaoFunctionGroup(functionValue) {
  return PB_FUNCTION_GROUP_BY_FUNCTION[functionValue] || "";
}

export function pbFunctionGroupsForFunctions(functionValues = []) {
  return [...new Set((functionValues || []).map(suggestPbCaoFunctionGroup).filter(Boolean))];
}

export const PB_FULLTIME_STANDARD_TEMPLATE_BODY = [
  "ARBEIDSOVEREENKOMST",
  "Fulltime dienstverband - CAO Particuliere Beveiliging",
  "",
  "Partijen",
  "Werkgever: {$bedrijf_statutaire_naam}, gevestigd aan {$bedrijf_adres_volledig}, ingeschreven bij de Kamer van Koophandel onder nummer {$bedrijf_kvk}, rechtsgeldig vertegenwoordigd door {$bedrijf_vertegenwoordiger_naam} in de functie van {$bedrijf_vertegenwoordiger_functie}, hierna: werkgever;",
  "",
  "Werknemer: {$medewerker_volledige_naam}, geboren op {$medewerker_geboortedatum} te {$medewerker_geboorteplaats}, wonende aan {$medewerker_adres_volledig}, hierna: werknemer;",
  "",
  "Werkgever en werknemer worden hierna gezamenlijk aangeduid als partijen en komen het volgende overeen.",
  "",
  "Artikel 1 - Indiensttreding en duur",
  "1.1 Werknemer treedt met ingang van {$contract_startdatum} bij werkgever in dienst.",
  "1.2 {$contract_duur_bepaling}",
  "1.3 {$contract_aanzegtermijn_bepaling}",
  "",
  "Artikel 2 - Toepasselijke cao",
  "2.1 Op deze arbeidsovereenkomst zijn de huidige en toekomstige bepalingen van de {$cao_naam} van toepassing, voor zover werkgever en werknemer onder de werkingssfeer daarvan vallen.",
  "2.2 Dwingend recht en bepalingen uit de toepasselijke cao waarvan niet ten nadele van werknemer mag worden afgeweken, gaan voor op strijdige bepalingen in deze arbeidsovereenkomst.",
  "2.3 Voor een niet-operationele functie blijven de uitzonderingen uit artikel 3 van de {$cao_naam} van toepassing. De gekozen functie- en loonindeling bepaalt daarom welke cao-onderdelen voor werknemer gelden.",
  "",
  "Artikel 3 - Proeftijd",
  "3.1 {$contract_proeftijd_bepaling}",
  "",
  "Artikel 4 - Functie, werkzaamheden en werkplek",
  "4.1 Werknemer treedt in dienst in de hoofdfunctie van {$hoofdfunctie}.",
  "4.2 De overeengekomen inzetbare functies zijn: {$functie_lijst}.",
  "4.3 {$contract_functie_indeling_bepaling}",
  "4.4 Werknemer verricht de werkzaamheden die bij de overeengekomen functie of functies horen en andere redelijke werkzaamheden die passen bij opleiding, ervaring, bevoegdheden, vakbekwaamheid en cao-indeling.",
  "4.5 Werknemer wordt niet ingezet voor werkzaamheden waarvoor de vereiste toestemming, legitimatie, opleiding, certificering of wettelijke bevoegdheid ontbreekt.",
  "4.6 {$contract_werkplek_bepaling}",
  "4.7 Als werknemer structureel andere werkzaamheden gaat verrichten, leggen partijen de gewijzigde functie en eventuele gevolgen voor de cao-indeling schriftelijk vast.",
  "",
  "Artikel 5 - Arbeidsduur, rooster en werktijden",
  "5.1 {$contract_arbeidsduur_bepaling}",
  "5.2 Werkgever stelt het rooster vast met inachtneming van de {$cao_naam}, de Arbeidstijdenwet en de daarin opgenomen regels over aankondiging, wijziging, rust en vrije tijd.",
  "5.3 Werknemer kan, voor zover passend bij de functie en binnen de toepasselijke regels, worden ingeroosterd op wisselende dagen en tijden, waaronder avond-, nacht-, weekend- en feestdagdiensten.",
  "5.4 Een wijziging van de structurele arbeidsduur wordt schriftelijk vastgelegd.",
  "",
  "Artikel 6 - Beloning",
  "6.1 {$contract_beloning_bepaling}",
  "6.2 {$contract_loonperiode_bepaling}",
  "6.3 Toeslagen voor bijzondere uren, feestdagen, overwerk, functiewaarneming en overige vergoedingen worden toegekend volgens de {$cao_naam} en de feitelijke werkzaamheden.",
  "6.4 Wijzigingen in loon, schaal of periodiek worden toegepast volgens de geldende cao en loontabel.",
  "",
  "Artikel 7 - Vakantie, vakantiebijslag en verlof",
  "7.1 {$contract_vakantie_bepaling}",
  "7.2 Werknemer ontvangt 8% vakantiebijslag over het daarvoor geldende bruto jaarloon. Opbouw en uitbetaling vinden plaats volgens de {$cao_naam} en de wet.",
  "7.3 Opname, verval en uitbetaling van vakantie-uren en overige verlofrechten worden toegepast volgens de wet en de {$cao_naam}.",
  "",
  "Artikel 8 - Pensioen en verzekering",
  "8.1 Werknemer neemt deel aan de regeling van {$pensioenregeling_naam}, voor zover de verplichtstelling en het pensioenreglement op werknemer van toepassing zijn.",
  "8.2 Werkgever houdt de werknemersbijdrage in voor zover dit volgens het pensioenreglement, de wet en de {$cao_naam} is toegestaan.",
  "8.3 Werkgever draagt zorg voor de collectieve ongevallenverzekering die de {$cao_naam} voorschrijft.",
  "",
  "Artikel 9 - Ziekte en re-integratie",
  "9.1 Werknemer meldt arbeidsongeschiktheid tijdig volgens het geldende verzuimprotocol.",
  "9.2 Tijdens arbeidsongeschiktheid gelden de wettelijke regels, de {$cao_naam} en redelijke controle- en re-integratievoorschriften van werkgever.",
  "9.3 Loondoorbetaling en re-integratieverplichtingen worden vastgesteld volgens de wet en de {$cao_naam}.",
  "",
  "Artikel 10 - Wpbr-toestemming, legitimatie en vakbekwaamheid",
  "10.1 {$contract_wpbr_bepaling}",
  "10.2 Werknemer informeert werkgever direct over feiten of omstandigheden die de vereiste toestemming, betrouwbaarheid, legitimatie, vakbekwaamheid of inzetbaarheid kunnen beïnvloeden.",
  "10.3 Ontbreekt of vervalt een vereiste toestemming, legitimatie of vakbekwaamheid, dan zet werkgever werknemer niet in voor werkzaamheden waarvoor die eis geldt. Partijen beoordelen de gevolgen volgens de wet, de {$cao_naam} en de omstandigheden; deze bepaling veroorzaakt geen automatische beëindiging van de arbeidsovereenkomst.",
  "",
  "Artikel 11 - Instructies, integriteit en veilige uitvoering",
  "11.1 Werknemer voert de werkzaamheden zorgvuldig, integer, betrouwbaar en professioneel uit en volgt redelijke bedrijfs-, veiligheids-, locatie- en objectinstructies op.",
  "11.2 Werknemer verricht geen werkzaamheden onder invloed van alcohol, drugs of andere middelen die een veilige en betrouwbare uitvoering kunnen beïnvloeden.",
  "11.3 Werknemer meldt incidenten, belangenconflicten en veiligheids- of integriteitsrisico's direct bij werkgever.",
  "",
  "Artikel 12 - Geheimhouding, privacy en informatiebeveiliging",
  "12.1 Werknemer houdt alle niet-openbare informatie geheim waarvan werknemer door het werk kennisneemt en waarvan de vertrouwelijke aard bekend is of redelijkerwijs duidelijk behoort te zijn.",
  "12.2 Daaronder valt in ieder geval bedrijfs-, klant-, personeels-, object-, alarm-, beeld-, transport-, onderzoeks- en systeeminformatie die werknemer via de functie, opdrachtgever, locatie of gebruikte systemen ontvangt.",
  "12.3 Werknemer gebruikt deze informatie uitsluitend voor het werk, deelt haar alleen met bevoegde personen die haar voor hun taak nodig hebben en gebruikt uitsluitend door werkgever goedgekeurde systemen en communicatiemiddelen.",
  "12.4 Werknemer meldt verlies, onbevoegde toegang, verkeerde verzending of een mogelijk datalek direct bij {$meldpunt_privacy_datalekken}.",
  "12.5 De geheimhoudingsplicht blijft na het einde van de arbeidsovereenkomst gelden zolang de informatie niet rechtmatig openbaar is geworden. Zij beperkt geen wettelijk toegestane melding bij een bevoegde instantie, vakbond, juridisch adviseur of meldpunt voor misstanden.",
  "",
  "Artikel 13 - Bedrijfsmiddelen",
  "13.1 Werknemer gebruikt verstrekte uniformen, legitimatiebewijzen, sleutels, passen, apparatuur, voertuigen, documenten, accounts en andere bedrijfsmiddelen zorgvuldig en volgens de instructies van werkgever.",
  "13.2 Verlies, diefstal, beschadiging of onbevoegd gebruik wordt direct gemeld.",
  "13.3 Werknemer geeft alle bedrijfsmiddelen op eerste verzoek en uiterlijk bij het einde van het dienstverband terug. Schade of kosten worden alleen verhaald voor zover wet en cao dit toelaten.",
  "",
  "Artikel 14 - Scholing",
  "14.1 Scholing die werkgever op grond van wet of cao verplicht moet aanbieden, wordt kosteloos aangeboden en geldt als arbeidstijd voor zover de wet of de {$cao_naam} dit voorschrijft.",
  "14.2 Voor een niet-verplichte opleiding kunnen partijen uitsluitend in een afzonderlijke, rechtsgeldige studiekostenovereenkomst aanvullende afspraken maken.",
  "",
  "Artikel 15 - Nevenwerkzaamheden",
  "15.1 Werknemer meldt nevenwerkzaamheden vooraf als deze kunnen leiden tot overtreding van arbeids- en rusttijden, een veiligheids- of integriteitsrisico, belangenverstrengeling, strijd met wettelijke voorschriften of risico voor vertrouwelijke informatie.",
  "15.2 Werkgever beperkt nevenwerkzaamheden alleen als daarvoor een objectieve reden bestaat en deelt die reden aan werknemer mee.",
  "",
  "Artikel 16 - Einde van de arbeidsovereenkomst",
  "16.1 {$contract_opzegtermijn_bepaling}",
  "16.2 De arbeidsovereenkomst eindigt van rechtswege op de dag waarop werknemer de AOW-gerechtigde leeftijd bereikt, tenzij partijen daarna rechtsgeldig voortzetten.",
  "16.3 Bij het einde van het dienstverband werkt werknemer mee aan een zorgvuldige overdracht en levert werknemer alle bedrijfsmiddelen en vertrouwelijke informatie in.",
  "",
  "Artikel 17 - Bedrijfsregelingen en slotbepalingen",
  "17.1 Bedrijfsregelingen en protocollen gelden alleen voor zover zij op werknemer van toepassing zijn en aan werknemer zijn verstrekt of toegankelijk zijn gemaakt. Wet, cao en deze arbeidsovereenkomst gaan voor bij strijdigheid.",
  "17.2 Wijzigingen van deze arbeidsovereenkomst worden schriftelijk of elektronisch aantoonbaar vastgelegd, tenzij wet of cao anders bepaalt.",
  "17.3 Als een bepaling nietig, vernietigbaar of niet afdwingbaar is, blijven de overige bepalingen gelden. Partijen vervangen de betrokken bepaling zo nodig door een rechtsgeldige bepaling die het doel zoveel mogelijk benadert.",
  "17.4 Op deze arbeidsovereenkomst is Nederlands recht van toepassing.",
  "",
  "Ondertekening",
  "Aldus overeengekomen en ondertekend te {$contract_ondertekeningsplaats} op {$contract_ondertekeningsdatum}.",
  "",
  "Voor werkgever:",
  "{$bedrijf_vertegenwoordiger_naam}",
  "{$bedrijf_vertegenwoordiger_functie}",
  "Handtekening: ______________________________",
  "",
  "Werknemer:",
  "{$medewerker_volledige_naam}",
  "Handtekening: ______________________________",
].join("\n");

export const CONTRACT_TEMPLATE_PLACEHOLDERS = [
  { key: "bedrijf_statutaire_naam", label: "Juridische bedrijfsnaam", source: "Bedrijfsprofiel" },
  { key: "bedrijf_handelsnaam", label: "Handelsnaam", source: "Bedrijfsprofiel" },
  { key: "bedrijf_rechtsvorm", label: "Rechtsvorm", source: "Bedrijfsprofiel" },
  { key: "bedrijf_adres_volledig", label: "Volledig bedrijfsadres", source: "Bedrijfsprofiel" },
  { key: "bedrijf_kvk", label: "KvK-nummer", source: "Bedrijfsprofiel" },
  { key: "bedrijf_btw_nummer", label: "Btw-nummer", source: "Bedrijfsprofiel" },
  { key: "bedrijf_email", label: "E-mailadres bedrijf", source: "Bedrijfsprofiel" },
  { key: "bedrijf_telefoon", label: "Telefoonnummer bedrijf", source: "Bedrijfsprofiel" },
  { key: "bedrijf_vertegenwoordiger_naam", label: "Naam vertegenwoordiger", source: "Contractwizard" },
  { key: "bedrijf_vertegenwoordiger_functie", label: "Functie vertegenwoordiger", source: "Contractwizard" },
  { key: "medewerker_volledige_naam", label: "Volledige naam medewerker", source: "Medewerkerprofiel" },
  { key: "medewerker_voornaam", label: "Voornaam medewerker", source: "Medewerkerprofiel" },
  { key: "medewerker_achternaam", label: "Achternaam medewerker", source: "Medewerkerprofiel" },
  { key: "medewerker_geboortedatum", label: "Geboortedatum", source: "Medewerkerprofiel" },
  { key: "medewerker_geboorteplaats", label: "Geboorteplaats", source: "Medewerkerprofiel" },
  { key: "medewerker_adres_volledig", label: "Volledig adres medewerker", source: "Medewerkerprofiel" },
  { key: "medewerker_email", label: "E-mailadres medewerker", source: "Medewerkerprofiel" },
  { key: "medewerker_telefoon", label: "Telefoonnummer medewerker", source: "Medewerkerprofiel" },
  { key: "cao_naam", label: "Naam toepasselijke cao", source: "CAO-keuze" },
  { key: "cao_versie", label: "CAO-versie", source: "CAO-configuratie" },
  { key: "cao_functiegroep", label: "CAO-functiegroep", source: "Contractwizard" },
  { key: "cao_functieniveau", label: "CAO-functieniveau", source: "Contractwizard" },
  { key: "salarisschaal", label: "Salarisschaal", source: "Loontabel" },
  { key: "periodiek", label: "Periodiek", source: "Loontabel" },
  { key: "bruto_uurloon", label: "Bruto uurloon", source: "Loontabel" },
  { key: "bruto_salaris_per_loonperiode", label: "Bruto salaris per loonperiode", source: "Afgeleid" },
  { key: "contract_startdatum", label: "Startdatum", source: "Contractwizard" },
  { key: "contract_einddatum", label: "Einddatum", source: "Contractwizard" },
  { key: "contract_duursoort", label: "Bepaalde of onbepaalde tijd", source: "Afgeleid" },
  { key: "contract_duur_omschrijving", label: "Leesbare contractduur", source: "Afgeleid" },
  { key: "contract_duur_bepaling", label: "Volledige looptijdbepaling", source: "Slim afgeleid" },
  { key: "contract_aanzegtermijn_bepaling", label: "Aanzegbepaling", source: "Slim afgeleid" },
  { key: "contract_proeftijd_bepaling", label: "Proeftijdbepaling", source: "Slim afgeleid" },
  { key: "contract_opzegtermijn_bepaling", label: "Opzegbepaling", source: "Slim afgeleid" },
  { key: "contract_arbeidsduur_bepaling", label: "Arbeidsduurbepaling", source: "Slim afgeleid" },
  { key: "contract_functie_indeling_bepaling", label: "Functie- en loonindeling", source: "Slim afgeleid" },
  { key: "contract_werkplek_bepaling", label: "Werkplek en werkgebied", source: "Contractwizard" },
  { key: "contract_beloning_bepaling", label: "Beloningsbepaling", source: "Slim afgeleid" },
  { key: "contract_loonperiode_bepaling", label: "Betaalperiode van het loon", source: "Slim afgeleid" },
  { key: "contract_vakantie_bepaling", label: "Vakantiebepaling", source: "Slim afgeleid" },
  { key: "contract_wpbr_bepaling", label: "Wpbr-bepaling", source: "Slim afgeleid" },
  { key: "hoofdfunctie", label: "Hoofdfunctie", source: "Contractwizard" },
  { key: "functie_lijst", label: "Alle overeengekomen functies", source: "Contractwizard" },
  { key: "nevenfuncties_lijst", label: "Aanvullende functies", source: "Contractwizard" },
  { key: "contracturen_per_week", label: "Contracturen per week", source: "Contractwizard" },
  { key: "contracturen_per_periode", label: "Contracturen per loonperiode", source: "Afgeleid" },
  { key: "pensioenregeling_naam", label: "Pensioenregeling", source: "CAO-configuratie" },
  { key: "meldpunt_privacy_datalekken", label: "Meldpunt privacy en datalekken", source: "Bedrijfsprofiel" },
  { key: "contract_ondertekeningsplaats", label: "Plaats ondertekening", source: "Contractwizard" },
  { key: "contract_ondertekeningsdatum", label: "Datum ondertekening", source: "Contractwizard" },
  { key: "exporteerdatum", label: "Exportdatum", source: "Systeem" },
];

const PLACEHOLDER_KEYS = new Set(CONTRACT_TEMPLATE_PLACEHOLDERS.map(item => item.key));

export const PB_FULLTIME_REQUIRED_PLACEHOLDERS = [
  "bedrijf_statutaire_naam",
  "bedrijf_adres_volledig",
  "bedrijf_kvk",
  "bedrijf_vertegenwoordiger_naam",
  "bedrijf_vertegenwoordiger_functie",
  "medewerker_volledige_naam",
  "medewerker_geboortedatum",
  "medewerker_geboorteplaats",
  "medewerker_adres_volledig",
  "cao_naam",
  "contract_startdatum",
  "contract_duur_bepaling",
  "contract_aanzegtermijn_bepaling",
  "contract_proeftijd_bepaling",
  "contract_opzegtermijn_bepaling",
  "contract_arbeidsduur_bepaling",
  "contract_functie_indeling_bepaling",
  "contract_werkplek_bepaling",
  "contract_beloning_bepaling",
  "contract_loonperiode_bepaling",
  "contract_vakantie_bepaling",
  "contract_wpbr_bepaling",
  "hoofdfunctie",
  "functie_lijst",
  "pensioenregeling_naam",
  "meldpunt_privacy_datalekken",
  "contract_ondertekeningsplaats",
  "contract_ondertekeningsdatum",
];

export function isKnownContractTemplatePlaceholder(key) {
  return PLACEHOLDER_KEYS.has(String(key || "").trim());
}

export function getContractTemplatePlaceholderDefinition(key) {
  return CONTRACT_TEMPLATE_PLACEHOLDERS.find(item => item.key === key) || null;
}

export const PB_FULLTIME_STANDARD_TEMPLATE = {
  id: PB_FULLTIME_STANDARD_TEMPLATE_ID,
  version: 1,
  name: "Fulltime dienstverband - CAO Particuliere Beveiliging",
  description: "Fulltime basismodel voor situaties waarin de CAO Particuliere Beveiliging daadwerkelijk van toepassing is, met slimme looptijd-, proeftijd-, arbeidsduur-, vakantie-, Wpbr- en opzegbepalingen.",
  template_type: "employment_contract",
  cao_key: CAO_PARTICULIERE_BEVEILIGING_KEY,
  contract_model: "fulltime_employment",
  body: PB_FULLTIME_STANDARD_TEMPLATE_BODY,
  required_placeholders: PB_FULLTIME_REQUIRED_PLACEHOLDERS,
  legal_basis: {
    cao_label: "CAO Particuliere Beveiliging 18 december 2024 tot en met 27 december 2026",
    cao_version: "Versie 3 - juli 2026",
    valid_from: "2024-12-18",
    valid_until: "2026-12-27",
    reviewed_at: "2026-07-10",
    applicability_note: "De vergunning bepaalt niet zelfstandig de cao. De werkingssfeer omvat volgens artikel 2 in beginsel ND/HND als Wpbr artikel 3 sub a, PAC, PGW en VTC, met cao-uitzonderingen voor onder meer bepaalde evenementen- en horecabeveiliging. BD, HBD en POB vallen niet alleen op grond van hun vergunning onder deze cao.",
    sources: [
      "https://www.beveiligingsbranche.nl/wp-content/uploads/CAO-PB-18-dec-2024-27-dec-2026-versie-3-juli-2026-.pdf",
      "https://www.beveiligingsbranche.nl/v-personeelswijzer/",
      "https://www.rijksoverheid.nl/vraag-en-antwoord/arbeidsovereenkomst-en-cao/wat-staat-er-in-een-arbeidsovereenkomst",
      "https://www.justis.nl/producten/particuliere-beveiliging-en-recherche/wat-is-de-wet-particuliere-beveiligingsorganisaties-en-recherchebureaus-wpbr",
    ],
  },
};

export function getStandardContractTemplatePreset(form = {}) {
  if (form.template_type !== PB_FULLTIME_STANDARD_TEMPLATE.template_type) return null;
  if (form.cao_key !== PB_FULLTIME_STANDARD_TEMPLATE.cao_key) return null;
  if (form.contract_model !== PB_FULLTIME_STANDARD_TEMPLATE.contract_model) return null;
  return PB_FULLTIME_STANDARD_TEMPLATE;
}
