import React from "react";
import { WEEKDAY_OPTIONS } from "./objectWarningAddressConfig";
import { TASK_SLOT_COUNT, TASK_SLOT_MINUTES } from "./objectTaskScheduleModel";

const HOURS = Array.from({ length: 25 }, (_, index) => index);
const timeLabel = slot => { const minutes = slot * TASK_SLOT_MINUTES; return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; };

export default function ObjectTaskScheduleGrid({ schedule, onPaint, painting, activeDayIndex = null }) {
  const disabled = dayIndex => Number.isInteger(activeDayIndex) && dayIndex !== activeDayIndex;
  return <div className="overflow-x-auto rounded-xl border border-border/70 bg-card/30"><div className="min-w-[2360px] select-none"><div className="flex h-9 border-b border-border/70"><span className="sticky left-0 z-20 w-12 shrink-0 bg-card" /><div className="relative flex-1">{HOURS.map(hour => <span key={hour} className={`absolute bottom-2 text-[10px] text-muted-foreground ${hour === 24 ? "-translate-x-full" : hour ? "-translate-x-1/2" : ""}`} style={{ left: `${hour / 24 * 100}%` }}>{String(hour).padStart(2, "0")}:00</span>)}</div></div>{WEEKDAY_OPTIONS.map((day, dayIndex) => <div key={day.key} className={`flex border-b border-border/70 last:border-b-0 ${disabled(dayIndex) ? "opacity-30" : ""}`}><span className="sticky left-0 z-20 flex h-14 w-12 shrink-0 items-center bg-card px-2 text-xs font-semibold">{day.label.slice(0, 2)}</span><div className="grid h-14 flex-1" style={{ gridTemplateColumns: `repeat(${TASK_SLOT_COUNT}, minmax(0, 1fr))` }}>{Array.from({ length: TASK_SLOT_COUNT }, (_, slot) => <button key={slot} type="button" disabled={disabled(dayIndex)} aria-label={`${day.label} ${timeLabel(slot)}`} title={`${day.label} ${timeLabel(slot)}–${timeLabel(slot + 1)}`} className={`h-full touch-none border-l bg-transparent focus-visible:z-10 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring ${slot % 12 === 0 ? "border-border" : slot % 3 === 0 ? "border-border/40" : "border-transparent"} ${schedule[dayIndex][slot] ? "bg-primary/25 hover:bg-primary/35" : "hover:bg-muted/60"}`} onPointerDown={event => { event.preventDefault(); if (!disabled(dayIndex)) onPaint(dayIndex, slot, true); }} onPointerEnter={() => { if (!disabled(dayIndex) && painting) onPaint(dayIndex, slot, false); }} />)}</div></div>)}</div></div>;
}