import React, { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, ClipboardList, Loader2, Plus, Search, X } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/use-toast";
import ObjectTaskDeleteDialog from "./ObjectTaskDeleteDialog";
import ObjectTaskTable from "./ObjectTaskTable";
import ObjectTaskWizard from "./ObjectTaskWizard";
import { taskTypeLabel } from "./objectTaskConfig";
import { listObjectSecurityPlans } from "./securityPlanWorkflow";
export default function ObjectTasksTab({ object, view, selectedRow, searchTerm, onSearchChange, onOpenCreate, onOpenEdit, onCloseView }) {
  const client = useQueryClient(), { toast } = useToast(), [deleteTarget, setDeleteTarget] = useState(null), key = ["object-card", object.id, "tasks"];
  const query = useQuery({ queryKey: key, queryFn: () => base44.entities.ObjectTaskDefinition.filter({ object_id: object.id, status: "active" }, "-updated_date", 500), retry: 1 });
  const planQuery = useQuery({ queryKey: ["object-card", object.id, "security-plans", "task-options"], queryFn: () => listObjectSecurityPlans({ customerId: object.customer_id, objectId: object.id, page: 1, pageSize: 250 }), enabled: view === "new" || view === "edit", retry: 1 });
  const tasks = (query.data || []).filter(task => task.status !== "archived"), current = view === "edit" ? tasks.find(task => task.id === selectedRow) : null, refresh = () => client.invalidateQueries({ queryKey: key });
  const save = useMutation({ mutationFn: form => current ? base44.entities.ObjectTaskDefinition.update(current.id, { ...form, version: Number(current.version || 1) + 1 }) : base44.entities.ObjectTaskDefinition.create({ ...form, customer_id: object.customer_id, object_id: object.id, status: "active", version: 1 }), onSuccess: async () => { await refresh(); onCloseView(); toast({ title: current ? "Taak opgeslagen" : "Taak toegevoegd" }); } });
  useEffect(() => { save.reset(); }, [selectedRow, view]);
  const remove = useMutation({ mutationFn: task => base44.entities.ObjectTaskDefinition.update(task.id, { status: "archived", version: Number(task.version || 1) + 1 }), onSuccess: async () => { await refresh(); setDeleteTarget(null); onCloseView(); toast({ title: "Taak gearchiveerd", description: "Bestaande planning en historie blijven behouden." }); }, onError: error => toast({ title: "Archiveren mislukt", description: error.message, variant: "destructive" }) });
  const rows = useMemo(() => { const term = searchTerm.trim().toLowerCase(); return tasks.filter(task => !term || [taskTypeLabel(task), task.instructions, task.start_time, task.end_time].some(value => String(value || "").toLowerCase().includes(term))); }, [tasks, searchTerm]);
  const archived = object.status === "archived", wizard = !archived && (view === "new" || Boolean(current));
  return <div className="flex min-h-[620px] flex-col bg-card/35 backdrop-blur-xl">{wizard && <ObjectTaskWizard key={current?.id || "new-task"} task={current} otherTasks={tasks.filter(item => item.id !== current?.id)} securityPlans={planQuery.data?.items || []} plansLoading={planQuery.isLoading} plansError={planQuery.error} saving={save.isPending} error={save.error} onSave={form => save.mutate(form)} onCancel={onCloseView} />}<div className="flex flex-col gap-3 border-b border-border/70 bg-card/25 px-4 py-3 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="text-sm font-semibold">Taken</h2><p className="mt-0.5 text-xs text-muted-foreground">{tasks.length} {tasks.length === 1 ? "taak" : "taken"} voor dit object</p></div><div className="flex gap-2"><div className="relative sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={searchTerm} onChange={event => onSearchChange(event.target.value)} placeholder="Zoek taak..." className="pl-9 pr-9" />{searchTerm && <button onClick={() => onSearchChange("")} className="absolute right-3 top-1/2 -translate-y-1/2"><X className="h-4 w-4" /></button>}</div>{!wizard && <Button size="sm" onClick={onOpenCreate} disabled={archived}><Plus /> Taak toevoegen</Button>}</div></div><div className="flex-1">{query.isLoading ? <div className="flex min-h-[360px] items-center justify-center text-xs text-muted-foreground"><Loader2 className="mr-2 animate-spin" /> Taken laden...</div> : query.isError ? <div className="m-4 flex gap-3 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><AlertCircle className="h-4 w-4" />{query.error.message}</div> : rows.length ? <ObjectTaskTable rows={rows} onEdit={task => !archived && onOpenEdit(task.id)} onDelete={setDeleteTarget} disabled={archived || remove.isPending} /> : <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><ClipboardList className="mb-3 h-5 w-5 text-muted-foreground" /><p className="text-sm font-medium">{searchTerm ? "Geen taken gevonden" : "Nog geen taken"}</p><p className="mt-1 max-w-md text-xs text-muted-foreground">{searchTerm ? "Pas de zoekopdracht aan." : "Leg vast welke taken op dit object moeten worden uitgevoerd."}</p>{!searchTerm && !archived && <Button size="sm" className="mt-4" onClick={onOpenCreate}><Plus /> Taak toevoegen</Button>}</div>}</div><ObjectTaskDeleteDialog task={deleteTarget} pending={remove.isPending} onClose={() => setDeleteTarget(null)} onConfirm={() => remove.mutate(deleteTarget)} /></div>;
}
