import React from "react";
import { Archive } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import ObjectRelationshipLogo from "./ObjectRelationshipLogo";
import { relationshipTypeLabel } from "./objectRelationshipConfig";

export default function ObjectRelationshipTable({ rows, onEdit, onArchive, disabled }) {
  return <><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow className="bg-card/25"><TableHead>Instantie</TableHead><TableHead>Relatie</TableHead><TableHead>Referentie</TableHead><TableHead>Telefoon</TableHead><TableHead>E-mail</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.id} className="group cursor-pointer" onClick={() => onEdit(row)}><TableCell><div className="flex items-center gap-3"><ObjectRelationshipLogo organization={row.organization} className="h-10 w-20" /><span className="font-medium">{row.organization?.name}</span></div></TableCell><TableCell>{relationshipTypeLabel(row)}</TableCell><TableCell>{row.reference_number || "—"}</TableCell><TableCell>{row.phone || "—"}</TableCell><TableCell>{row.email || "—"}</TableCell><TableCell><Button variant="ghost" size="icon" disabled={disabled} className="opacity-0 group-hover:opacity-100" onClick={event => { event.stopPropagation(); onArchive(row); }}><Archive className="text-destructive" /></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y divide-border md:hidden">{rows.map(row => <article key={row.id} className="px-4 py-3"><button type="button" onClick={() => onEdit(row)} className="flex w-full items-center gap-3 text-left"><ObjectRelationshipLogo organization={row.organization} className="h-10 w-16" /><span><span className="block text-sm font-medium">{row.organization?.name}</span><span className="text-xs text-muted-foreground">{relationshipTypeLabel(row)}{row.reference_number ? ` · ${row.reference_number}` : ""}</span></span></button><button type="button" disabled={disabled} onClick={() => onArchive(row)} className="mt-2 text-xs font-medium text-destructive">Archiveren</button></article>)}</div></>;
}