import React, { useEffect, useMemo, useRef, useState } from "react";
import ObjectTaskScheduleGrid from "./ObjectTaskScheduleGrid";
import { EMPTY_TASK_SCHEDULE, TASK_SLOT_MINUTES, taskPeriodsToSchedule, taskScheduleToPeriods } from "./objectTaskScheduleModel";
const dayIndexForDate = value => { if (!value) return null; const [year, month, day] = value.split("-").map(Number), index = new Date(year, month - 1, day).getDay(); return index === 0 ? 6 : index - 1; };
export default function ObjectTaskSchedule({ periods, onChange, oneTimeDate }) {
  const [tool, setTool] = useState("available"), [painting, setPainting] = useState(false), activeDayIndex = dayIndexForDate(oneTimeDate);
  const schedule = useMemo(() => taskPeriodsToSchedule(periods || []), [periods]), scheduleRef = useRef(schedule);
  useEffect(() => { scheduleRef.current = schedule; }, [schedule]);
  useEffect(() => { const stop = () => setPainting(false); window.addEventListener("pointerup", stop); return () => window.removeEventListener("pointerup", stop); }, []);
  const commit = next => { scheduleRef.current = next; onChange(taskScheduleToPeriods(next)); };
  const paint = (dayIndex, slot, start) => { if (start) setPainting(true); const next = scheduleRef.current.map(day => [...day]); next[dayIndex][slot] = tool; commit(next); };
  const preset = type => { const next = EMPTY_TASK_SCHEDULE(), days = Number.isInteger(activeDayIndex) ? [next[activeDayIndex]] : next; if (type === "all") days.forEach(day => day.fill("available")); if (type === "business") days.slice(0, Number.isInteger(activeDayIndex) ? 1 : 5).forEach(day => day.fill("available", 8 * 60 / TASK_SLOT_MINUTES, 18 * 60 / TASK_SLOT_MINUTES)); commit(next); };
  return <fieldset className="space-y-3"><legend className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Taakrooster *</legend><div className="flex flex-wrap gap-2">{!Number.isInteger(activeDayIndex) && <button type="button" onClick={() => preset("business")} className="rounded-xl border border-border/70 bg-card/45 px-3 py-2 text-xs font-medium hover:border-primary/40">Werkdagen 08:00–18:00</button>}<button type="button" onClick={() => preset("all")} className="rounded-xl border border-border/70 bg-card/45 px-3 py-2 text-xs font-medium hover:border-primary/40">{Number.isInteger(activeDayIndex) ? "Hele dag" : "24/7 invullen"}</button><button type="button" onClick={() => preset("empty")} className="rounded-xl border border-border/70 bg-card/45 px-3 py-2 text-xs font-medium hover:border-primary/40">Rooster wissen</button></div><div className="flex gap-2"><button type="button" onClick={() => setTool("available")} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-medium ${tool === "available" ? "border-primary/60 bg-primary/10" : "border-border/70 bg-card/45"}`}><span className="h-3 w-3 rounded-sm border border-primary/40 bg-primary/25" />Taak uitvoeren</button><button type="button" onClick={() => setTool(null)} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-medium ${tool === null ? "border-primary/60 bg-primary/10" : "border-border/70 bg-card/45"}`}><span className="h-3 w-3 rounded-sm border border-border bg-card" />Wissen</button></div><ObjectTaskScheduleGrid schedule={schedule} onPaint={paint} painting={painting} activeDayIndex={activeDayIndex} /><p className="text-xs text-muted-foreground">Sleep horizontaal door het ruime rooster; ieder blok staat voor 5 minuten.</p></fieldset>;
}