import React, { useEffect, useMemo, useRef, useState } from "react";
import WarningAvailabilityGrid from "./WarningAvailabilityGrid";
import ObjectTaskTimePopup from "./ObjectTaskTimePopup";
import { WEEKDAY_OPTIONS } from "./objectWarningAddressConfig";
import { EMPTY_SCHEDULE, periodsToSchedule, scheduleToPeriods } from "./warningAvailabilityScheduleModel";
const dayIndexForDate = value => { if (!value) return null; const [year, month, day] = value.split("-").map(Number), index = new Date(year, month - 1, day).getDay(); return index === 0 ? 6 : index - 1; };
export default function ObjectTaskSchedule({ periods, onChange, oneTimeDate, executionMode, durationMinutes }) {
  const continuous = executionMode === "continuous";
  const [tool, setTool] = useState("available"), [painting, setPainting] = useState(false), [editor, setEditor] = useState(null), activeDayIndex = dayIndexForDate(oneTimeDate);
  const schedule = useMemo(() => periodsToSchedule((periods || []).map(period => ({ ...period, kind: "available" }))), [periods]), scheduleRef = useRef(schedule);
  useEffect(() => { scheduleRef.current = schedule; }, [schedule]);
  useEffect(() => { const stop = () => setPainting(false); window.addEventListener("pointerup", stop); return () => window.removeEventListener("pointerup", stop); }, []);
  const commit = next => { scheduleRef.current = next; onChange(scheduleToPeriods(next).map(({ kind: _kind, ...period }) => period)); };
  const paint = (dayIndex, slot, start, active) => { if (!continuous) { const dayKey = WEEKDAY_OPTIONS[dayIndex].key; if (tool === null) { if (!active) return; onChange((periods || []).filter(period => !(period.days?.includes(dayKey) && toMinutes(period.start_time) === active.interval.start && toMinutes(period.end_time) === active.interval.end))); return; } const startMinute = slot * 30, endMinute = startMinute + Number(durationMinutes || 0); if (!durationMinutes || endMinute > 1440 || (periods || []).some(period => period.days?.includes(dayKey) && toMinutes(period.start_time) < endMinute && toMinutes(period.end_time) > startMinute)) return; onChange([...(periods || []), { days: [dayKey], start_time: toTime(startMinute), end_time: toTime(endMinute) }]); return; } if (start) setPainting(true); const next = scheduleRef.current.map(day => [...day]); next[dayIndex][slot] = tool; commit(next); };
  const preset = type => { const next = EMPTY_SCHEDULE(), days = Number.isInteger(activeDayIndex) ? [next[activeDayIndex]] : next; if (type === "all") days.forEach(day => day.fill("available")); if (type === "business") days.slice(0, Number.isInteger(activeDayIndex) ? 1 : 5).forEach(day => day.fill("available", 16, 36)); commit(next); };
  const toMinutes = value => value === "24:00" ? 1440 : Number(value.slice(0, 2)) * 60 + Number(value.slice(3));
  const toTime = value => value === 1440 ? "24:00" : `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`;
  const openEditor = interval => { const dayKey = WEEKDAY_OPTIONS[interval.dayIndex].key; const period = (periods || []).find(item => item.days?.includes(dayKey) && toMinutes(item.start_time) === interval.start && toMinutes(item.end_time) === interval.end); setEditor({ ...interval, dayKey, dayLabel: WEEKDAY_OPTIONS[interval.dayIndex].label, start_time: period?.start_time || toTime(interval.start), end_time: period?.end_time || toTime(interval.end) }); };
  const saveExactTime = (start_time, end_time) => { const next = (periods || []).filter(period => !(period.days?.includes(editor.dayKey) && toMinutes(period.start_time) < editor.end && toMinutes(period.end_time) > editor.start)); next.push({ days: [editor.dayKey], start_time, end_time }); onChange(next); setEditor(null); };
  return <fieldset className="space-y-3"><legend className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Taakrooster *</legend><div className="flex flex-wrap gap-2">{continuous && !Number.isInteger(activeDayIndex) && <button type="button" onClick={() => preset("business")} className="rounded-xl border border-border/70 bg-card/45 px-3 py-2 text-xs font-medium hover:border-primary/40">Werkdagen 08:00–18:00</button>}{continuous && <button type="button" onClick={() => preset("all")} className="rounded-xl border border-border/70 bg-card/45 px-3 py-2 text-xs font-medium hover:border-primary/40">{Number.isInteger(activeDayIndex) ? "Hele dag" : "24/7 invullen"}</button>}<button type="button" onClick={() => { if (continuous) preset("empty"); else onChange([]); }} className="rounded-xl border border-border/70 bg-card/45 px-3 py-2 text-xs font-medium hover:border-primary/40">Rooster wissen</button></div><div className="flex gap-2"><button type="button" onClick={() => setTool("available")} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-medium ${tool === "available" ? "border-primary/60 bg-primary/10" : "border-border/70 bg-card/45"}`}><span className="h-3 w-3 rounded-sm border border-primary/40 bg-primary/25" />{continuous ? "Taak uitvoeren" : `Taak plaatsen (${durationMinutes} min.)`}</button><button type="button" onClick={() => setTool(null)} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-medium ${tool === null ? "border-primary/60 bg-primary/10" : "border-border/70 bg-card/45"}`}><span className="h-3 w-3 rounded-sm border border-border bg-card" />Wissen</button></div><WarningAvailabilityGrid schedule={schedule} exactPeriods={(periods || []).map(period => ({ ...period, kind: "available" }))} onPaint={paint} onIntervalClick={openEditor} painting={painting} tool={tool} activeDayIndex={activeDayIndex} /><p className="text-xs text-muted-foreground">{continuous ? "Sleep over blokken van 30 minuten. Klik op een ingetekende taak om exacte tijden op te geven." : `Klik in het rooster om een losse taak van ${durationMinutes} minuten te plaatsen. Klik op de taak om de exacte starttijd aan te passen.`}</p>{editor && <ObjectTaskTimePopup editor={editor} fixedDuration={continuous ? null : durationMinutes} onClose={() => setEditor(null)} onSave={saveExactTime} />}</fieldset>;
}