import React, { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, Building2, Loader2, Plus, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/use-toast";
import ObjectRelationshipArchiveDialog from "./ObjectRelationshipArchiveDialog";
import ObjectRelationshipTable from "./ObjectRelationshipTable";
import ObjectRelationshipWizard from "./ObjectRelationshipWizard";
import { archiveObjectRelationship, archiveObjectRelationshipKey, createObjectRelationshipKey, listObjectRelationships, saveObjectRelationship, updateObjectRelationshipKey } from "./objectRelationshipWorkflow";

export default function ObjectRelationshipsTab({ object, view, selectedRow, searchTerm, onSearchChange, onOpenCreate, onOpenEdit, onCloseView }) {
  const client = useQueryClient(), { toast } = useToast(), saveKey = useRef(null), queryKey = ["object-card", object.id, "relationships"];
  const [archiveTarget, setArchiveTarget] = useState(null);
  const query = useQuery({ queryKey, queryFn: () => listObjectRelationships({ customerId: object.customer_id, objectId: object.id }), retry: 1 });
  const relationships = query.data?.items || [], organizations = query.data?.organizations || [], current = view === "edit" ? relationships.find(item => item.id === selectedRow) : null;
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey }), client.invalidateQueries({ queryKey: ["object-card", object.id, "logbook"] })]);
  const save = useMutation({ mutationFn: form => saveObjectRelationship({ customerId: object.customer_id, objectId: object.id, relationship: current, form, idempotencyKey: saveKey.current }), onSuccess: async () => { await refresh(); saveKey.current = null; onCloseView(); toast({ title: current ? "Relatie opgeslagen" : "Relatie toegevoegd" }); } });
  const archive = useMutation({ mutationFn: relationship => archiveObjectRelationship({ customerId: object.customer_id, objectId: object.id, relationship, idempotencyKey: archiveObjectRelationshipKey() }), onSuccess: async () => { await refresh(); setArchiveTarget(null); onCloseView(); toast({ title: "Relatie gearchiveerd" }); }, onError: error => toast({ title: "Archiveren mislukt", description: error.message, variant: "destructive" }) });
  useEffect(() => { saveKey.current = null; save.reset(); }, [selectedRow, view]);
  const rows = useMemo(() => { const term = searchTerm.trim().toLowerCase(); return relationships.filter(item => !term || [item.organization?.name, item.custom_relation_label, item.reference_number, item.phone, item.email].some(value => String(value || "").toLowerCase().includes(term))); }, [relationships, searchTerm]);
  const archived = object.status === "archived", showWizard = !archived && (view === "new" || Boolean(current));
  const saveForm = form => { if (!saveKey.current) saveKey.current = current ? updateObjectRelationshipKey() : createObjectRelationshipKey(); save.mutate(form); };
  return <div className="flex min-h-[620px] flex-col bg-card/35 backdrop-blur-xl">{showWizard && <ObjectRelationshipWizard relationship={current} organizations={organizations} onCancel={onCloseView} onSave={saveForm} saving={save.isPending} error={save.error} />}<div className="flex flex-col gap-3 border-b border-border/70 bg-card/25 px-4 py-3 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="text-sm font-semibold">Relaties</h2><p className="mt-0.5 text-xs text-muted-foreground">{relationships.length} derde instanti{relationships.length === 1 ? "e" : "es"} bij dit object</p></div><div className="flex gap-2"><div className="relative sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={searchTerm} onChange={event => onSearchChange(event.target.value)} placeholder="Zoek relatie..." className="h-9 pl-9 pr-9" />{searchTerm && <button onClick={() => onSearchChange("")} className="absolute right-2.5 top-1/2 -translate-y-1/2"><X className="h-4 w-4" /></button>}</div>{!showWizard && <Button size="sm" onClick={onOpenCreate} disabled={archived}><Plus /> Relatie toevoegen</Button>}</div></div><div className="flex-1">{query.isLoading ? <div className="flex min-h-[360px] items-center justify-center text-xs text-muted-foreground"><Loader2 className="mr-2 animate-spin" /> Relaties laden...</div> : query.isError ? <div className="m-4 flex gap-3 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><AlertCircle className="h-4 w-4" />{query.error.message}</div> : rows.length ? <ObjectRelationshipTable rows={rows} onEdit={row => !archived && onOpenEdit(row.id)} onArchive={setArchiveTarget} disabled={archived || archive.isPending} /> : <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><Building2 className="mb-3 h-5 w-5 text-muted-foreground" /><p className="text-sm font-medium">{searchTerm ? "Geen relaties gevonden" : "Nog geen relaties"}</p><p className="mt-1 max-w-md text-xs text-muted-foreground">{searchTerm ? "Pas de zoekopdracht aan." : "Voeg een meldkamer, installateur, videocentrale of andere derde instantie toe."}</p>{!searchTerm && !archived && <Button size="sm" className="mt-4" onClick={onOpenCreate}><Plus /> Relatie toevoegen</Button>}</div>}</div><ObjectRelationshipArchiveDialog relationship={archiveTarget} open={Boolean(archiveTarget)} pending={archive.isPending} onOpenChange={open => !open && !archive.isPending && setArchiveTarget(null)} onConfirm={() => archive.mutate(archiveTarget)} /></div>;
}