import React from "react";
import { Pencil, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { WEEKDAYS, recurrenceLabel, taskTypeLabel } from "./objectTaskConfig";
const days = task => task.weekdays?.length ? task.weekdays.slice().sort().map(value => WEEKDAYS.find(day => day.value === value)?.label).join(", ") : "—";
export default function ObjectTaskTable({ rows, onEdit, onDelete, disabled }) {
  return <><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow className="bg-card/25"><TableHead>Taak</TableHead><TableHead>Uitvoering</TableHead><TableHead>Tijd</TableHead><TableHead>Herhaling</TableHead><TableHead>Dagen</TableHead><TableHead className="w-24" /></TableRow></TableHeader><TableBody>{rows.map(task => <TableRow key={task.id} className="group"><TableCell className="font-medium">{taskTypeLabel(task)}</TableCell><TableCell><Badge variant="outline">{task.execution_mode === "continuous" ? "Aaneengesloten" : `${task.duration_minutes} min binnen venster`}</Badge></TableCell><TableCell>{task.start_time} – {task.end_time}{task.end_time <= task.start_time ? " (+1)" : ""}</TableCell><TableCell>{recurrenceLabel(task)}</TableCell><TableCell>{days(task)}</TableCell><TableCell><div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => onEdit(task)} disabled={disabled}><Pencil /></Button><Button variant="ghost" size="icon" onClick={() => onDelete(task)} disabled={disabled}><Trash2 className="text-destructive" /></Button></div></TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y divide-border md:hidden">{rows.map(task => <article key={task.id} className="space-y-2 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{taskTypeLabel(task)}</p><p className="mt-1 text-xs text-muted-foreground">{task.start_time} – {task.end_time} · {task.execution_mode === "continuous" ? "aaneengesloten" : `${task.duration_minutes} min`}</p></div><div className="flex"><Button variant="ghost" size="icon" disabled={disabled} onClick={() => onEdit(task)}><Pencil /></Button><Button variant="ghost" size="icon" disabled={disabled} onClick={() => onDelete(task)}><Trash2 className="text-destructive" /></Button></div></div><p className="text-xs text-muted-foreground">{recurrenceLabel(task)}{days(task) !== "—" ? ` · ${days(task)}` : ""}</p></article>)}</div></>;
}