import React from "react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Field, StepHeading } from "./ObjectWizardUi";
import ObjectKeySetChoice from "./ObjectKeySetChoice";
import { OBJECT_KEY_STATUS_OPTIONS } from "./objectKeyConfig";

export default function ObjectKeyDetailsStep({ form, sets, onChange, onSet, readOnlySet = false }) {
  const selectedSet = sets.find(set => set.id === form.key_set_id);
  return <><StepHeading title="Hoe is dit toegangsmiddel herkenbaar?" /><div className="grid gap-4 md:grid-cols-2"><Field label="Serie-, pas- of tagnummer" htmlFor="object-key-serial" hint="Het herkenningsnummer op de sleutel, pas, tag of afstandsbediening."><Input id="object-key-serial" value={form.serial_number} onChange={event => onChange("serial_number", event.target.value)} placeholder="Nummer op het middel" autoFocus /></Field><Field label="Status" htmlFor="object-key-status"><Select value={form.status} onValueChange={value => onChange("status", value)}><SelectTrigger id="object-key-status"><SelectValue /></SelectTrigger><SelectContent>{OBJECT_KEY_STATUS_OPTIONS.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></Field></div>{readOnlySet ? <div className="rounded-lg border border-border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Sleutelset</p><p className="mt-1 text-sm font-medium">{selectedSet?.display_label || "Bestaande sleutelset"}</p><p className="mt-0.5 text-xs text-muted-foreground">Sleutelnummer {selectedSet?.key_number || "—"}. Verplaatsen naar een andere fysieke set gebeurt gecontroleerd via archiveren en opnieuw registreren.</p></div> : <ObjectKeySetChoice sets={sets} setId={form.key_set_id} createNew={form.create_new_set} setKeyNumber={form.set_key_number} onSetKeyNumberChange={value => onChange("set_key_number", value)} onSelect={onSet} />}</>;
}