import React, { useId } from 'react';
import type { Floor, Point } from './model';
import { centre, distance, polygonArea, wallPoint, floorBounds } from './geometry';
import { catalogItem } from './catalog';
export type Layers = { background: boolean; rooms: boolean; dimensions: boolean; security: boolean; fire: boolean; evacuation: boolean; labels: boolean };
export const defaultLayers: Layers = { background: true, rooms: true, dimensions: true, security: true, fire: true, evacuation: true, labels: true };
export function SymbolGlyph({kind, size = 26, solid = false}: {kind:string;size?:number;solid?:boolean}) {
 const color = catalogItem(kind).color; const filled = solid && ['Brandveiligheid','Ontruiming'].includes(catalogItem(kind).group);
 const glyphs:Record<string,React.ReactNode> = {
  camera:<><path d="M6 9h11v7H6zM17 11l5-3v9l-5-3M10 16v4M6 20h8"/><circle cx="11.5" cy="12.5" r="2"/></>,
  motion_detector:<><path d="M9 5h8v7H9zM7 15q6 6 12 0M4 18q9 9 18 0"/><circle cx="13" cy="8" r=".8"/></>,
  alarm_panel:<><rect x="6" y="4" width="14" height="19" rx="2"/><path d="M9 8h8M9 12h2m4 0h2m-8 4h2m4 0h2m-8 4h8"/></>,
  access_control:<><rect x="8" y="4" width="11" height="19" rx="2"/><path d="M11 8h5M11 12h5M3 9q5 4 0 8"/><circle cx="13.5" cy="18" r="1"/></>,
  smoke_detector:<><path d="M5 14h17l-3 5H8zM8 8q-2-2 0-4m5 5q-2-2 0-4m5 3q-2-2 0-4"/><circle cx="14" cy="16" r=".7"/></>,
  manual_call_point:<><rect x="5" y="5" width="17" height="17" rx="1"/><circle cx="13.5" cy="13.5" r="4"/><path d="M9 13h9M14 9v8"/></>,
  fire_extinguisher:<><rect x="9" y="9" width="8" height="14" rx="2"/><path d="M11 9V5h6M10 5h-3M16 6q6 0 5 9M12 3h3"/><path d="M9 15h8"/></>,
  fire_hose:<><circle cx="13" cy="12" r="7"/><circle cx="13" cy="12" r="3"/><path d="M20 12v8h-9M7 22h4v-4"/></>,
  aed:<><path d="M13.5 22S3 15 4 9q1-8 9.5-2Q22 1 23 9q1 6-9.5 13z"/><path d="M14 7l-5 8h5l-2 5 7-9h-5z" fill="currentColor" strokeWidth=".6"/></>,
  emergency_exit:<><path d="M5 23V4h8v19M13 14h11m-4-4 4 4-4 4M5 23h12"/><circle cx="9" cy="13" r=".5"/></>,
  assembly_point:<><circle cx="11" cy="12" r="2"/><circle cx="17" cy="12" r="2"/><path d="M8 21v-4q3-3 6 0v4M15 21v-4q3-3 5 0v4M3 4l4 4M3 8h4V4m17 0-4 4m0-4v4h4"/></>,
  'you_are_here':<><circle cx="13.5" cy="13.5" r="7" fill="currentColor" stroke="white"/><circle cx="13.5" cy="13.5" r="11"/><path d="M13.5 1v4m0 17v4M1 13.5h4m17 0h4"/></>,
  first_aid:<path d="M10 4h7v6h6v7h-6v6h-7v-6H4v-7h6z" fill="currentColor"/>,
  stairs:<><rect x="3" y="3" width="21" height="21"/><path d="M3 7h21M3 11h21M3 15h21M3 19h21M13 22V5m-3 3 3-3 3 3"/></>,
  lift:<><rect x="4" y="7" width="19" height="17"/><path d="M13.5 7v17M7 3h5m-2-2 2 2-2 2m10-4-2 2 2 2"/></>,
  electrical:<path d="M15 2 6 15h7l-1 10 10-15h-8z" fill="currentColor"/>,
 };
 return <svg width={size} height={size} viewBox="0 0 27 27" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" style={{color}} aria-hidden="true">{filled&&<rect x="0" y="0" width="27" height="27" rx="2" fill={color} stroke="none"/>}<g stroke={filled?'white':'currentColor'} style={{color:filled?'white':color}} transform={filled?'translate(2 2) scale(.85)':undefined}>{glyphs[kind] || glyphs.alarm_panel}</g></svg>;
}
export function isSymbolVisible(kind: string, profile: 'installation'|'evacuation', layers: Layers) { const group = catalogItem(kind).group; if (group === 'Beveiliging') return profile === 'installation' && layers.security; if (group === 'Brandveiligheid') return layers.fire; if (group === 'Ontruiming') return layers.evacuation; return true; }
export type RendererProps = { floor: Floor; backgroundUrls?: Record<string,string>; layers?: Partial<Layers>; profile?: 'installation'|'evacuation'; selectedId?: string; onElementPointerDown?: (event:React.PointerEvent,id:string,type:string) => void; standalone?: boolean; className?: string; dimensions?: boolean; viewpoint?:{position:Point;rotation:number}; printMode?:boolean; showSymbolLabels?:boolean; printScale?:number };
export default function FloorPlanRenderer({ floor, backgroundUrls = {}, layers: layerOverrides, profile = 'installation', selectedId, onElementPointerDown, standalone = true, className, dimensions = true, viewpoint, printMode = false, showSymbolLabels = true, printScale = 100 }:RendererProps) {
 const counterRotation = printMode ? (viewpoint?.rotation || 0) : 0; const directionalSymbols = new Set(['camera','motion_detector','emergency_exit','stairs','lift','access_control']); const symbolFactor = printMode ? Math.max(1, .008*printScale/.64) : 1; const labelSize = printMode ? Math.max(.19, .0024*printScale) : .19; const dimensionSize = printMode ? Math.max(.23,.0024*printScale) : .23; const layers = {...defaultLayers,...layerOverrides}; const marker = `arrow-${useId().replace(/:/g,'')}`; const b = floorBounds(floor); const interact = (id:string,type:string) => ({ onPointerDown: (event:React.PointerEvent) => onElementPointerDown?.(event,id,type), style: { cursor: onElementPointerDown ? 'pointer' : 'inherit' } });
 const content = <>
  <defs><marker id={marker} markerWidth="4" markerHeight="4" refX="3" refY="2" orient="auto" markerUnits="strokeWidth"><path d="M0 0 4 2 0 4z" fill="#19855b"/></marker></defs>
  {layers.background && floor.background && backgroundUrls[floor.background.fileId] && <image href={backgroundUrls[floor.background.fileId]} x={floor.background.origin.x} y={-floor.background.origin.y-floor.background.height*floor.background.metresPerPixel} width={floor.background.width*floor.background.metresPerPixel} height={floor.background.height*floor.background.metresPerPixel} opacity={floor.background.opacity} style={{pointerEvents:'none'}}/>}
  {layers.rooms && floor.rooms.map(room => { const c = centre(room.polygon); return <g key={room.id} {...interact(room.id,'room')}><polygon points={room.polygon.map(p=>`${p.x},${-p.y}`).join(' ')} fill={selectedId===room.id?'#e8efff':'#f5f5f1'} fillOpacity=".7" stroke={selectedId===room.id?'#3b64d9':'#dedfd8'} strokeWidth=".025"/>{layers.labels && <text transform={counterRotation?`rotate(${counterRotation} ${c.x} ${-c.y})`:undefined} x={c.x} y={-c.y} fontSize={printMode?Math.max(.28,.0028*printScale):.28} fill="#65717b" stroke="white" strokeWidth=".06" paintOrder="stroke" textAnchor="middle" dominantBaseline="middle">{room.label}<tspan x={c.x} dy={printMode?Math.max(.38,.0038*printScale):.38} fontSize={printMode?Math.max(.2,.0024*printScale):.2} fill="#939ca3">{polygonArea(room.polygon).toLocaleString('nl-NL',{maximumFractionDigits:1})} m²</tspan></text>}</g>;})}
  {floor.walls.map(wall => { const middle = centre([wall.start,wall.end]); const length = distance(wall.start,wall.end); let degrees=-Math.atan2(wall.end.y-wall.start.y,wall.end.x-wall.start.x)*180/Math.PI; if(degrees>90||degrees< -90)degrees+=180; return <g key={wall.id} {...interact(wall.id,'wall')}><line x1={wall.start.x} y1={-wall.start.y} x2={wall.end.x} y2={-wall.end.y} stroke="transparent" strokeWidth={Math.max(.4,wall.thickness)} /><line x1={wall.start.x} y1={-wall.start.y} x2={wall.end.x} y2={-wall.end.y} stroke={selectedId===wall.id?'#3466dd':'#344148'} strokeWidth={wall.thickness} strokeLinecap="square"/>{dimensions && layers.dimensions && <g transform={`translate(${middle.x} ${-middle.y}) rotate(${degrees})`}><text transform={counterRotation?`rotate(${counterRotation-degrees} 0 ${-wall.thickness/2-.15})`:undefined} y={-wall.thickness/2-.15} fontSize={dimensionSize} textAnchor="middle" fill="#677782" stroke="white" strokeWidth=".06" paintOrder="stroke">{length.toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})} m</text></g>}</g>;})}
  {floor.openings.map(opening => { const wall = floor.walls.find(w => w.id===opening.wallId); if(!wall)return null; const p = wallPoint(wall,opening.offset); const degrees=-Math.atan2(wall.end.y-wall.start.y,wall.end.x-wall.start.x)*180/Math.PI; const w=opening.width; const h=wall.thickness; const hinge=opening.hinge==='right'?w:0; const edge=opening.hinge==='right'?0:w; const swing=opening.swing==='in'?-1:1; return <g key={opening.id} transform={`translate(${p.x} ${-p.y}) rotate(${degrees})`} {...interact(opening.id,'opening')}><rect x="-.015" y={-h/2-.012} width={w+.03} height={h+.024} fill="white"/><rect x="0" y={-.2} width={w} height=".4" fill="transparent"/>{opening.type==='window'?<><path d={`M0 ${-h/2}H${w}M0 ${h/2}H${w}M0 0H${w}`} stroke={selectedId===opening.id?'#3466dd':'#70a2ad'} strokeWidth=".035"/></>:opening.type==='door'?<><path d={`M${hinge} 0V${swing*w}`} stroke={selectedId===opening.id?'#3466dd':'#556772'} strokeWidth=".055"/><path d={`M${edge} 0 A${w} ${w} 0 0 ${(opening.hinge==='left')===(swing>0)?1:0} ${hinge} ${swing*w}`} stroke="#9aa6aa" strokeDasharray=".05 .03" strokeWidth=".02" fill="none"/></>:null}</g>;})}
  {layers.evacuation && floor.routes.map(route=><g key={route.id} {...interact(route.id,'route')}><polyline points={route.points.map(p=>`${p.x},${-p.y}`).join(' ')} fill="none" stroke="transparent" strokeWidth=".5"/><polyline points={route.points.map(p=>`${p.x},${-p.y}`).join(' ')} fill="none" stroke={selectedId===route.id?'#3466dd':'#19855b'} strokeWidth=".11" strokeLinejoin="round" strokeLinecap="round" markerMid={`url(#${marker})`} markerEnd={`url(#${marker})`}/>{selectedId===route.id && route.points.map((p,i)=><circle key={i} cx={p.x} cy={-p.y} r=".09" fill="white" stroke="#3466dd" strokeWidth=".03"/>)}</g>)}
  {floor.symbols.filter(s=>isSymbolVisible(s.kind,profile,layers) && !(viewpoint&&s.kind==='you_are_here')).map(symbol=><g key={symbol.id} {...interact(symbol.id,'symbol')}><g transform={`translate(${symbol.position.x} ${-symbol.position.y}) rotate(${-symbol.rotation+(directionalSymbols.has(symbol.kind)?0:counterRotation)}) scale(${symbolFactor})`}>{selectedId===symbol.id&&<rect x="-.42" y="-.42" width=".84" height=".84" rx=".08" fill="#e7eeff" stroke="#3466dd" strokeWidth=".03"/>}<rect x="-.32" y="-.32" width=".64" height=".64" rx=".06" fill="white" stroke={catalogItem(symbol.kind).color} strokeWidth=".025"/><g transform="translate(-.28 -.28) scale(.02074)"><SymbolGlyph kind={symbol.kind} solid/></g></g>{layers.labels && showSymbolLabels && (!printMode || profile==='installation' || symbol.kind==='you_are_here') && <text transform={counterRotation?`rotate(${counterRotation} ${symbol.position.x} ${-symbol.position.y+.53*symbolFactor})`:undefined} x={symbol.position.x} y={-symbol.position.y+.53*symbolFactor} fontSize={labelSize} fill="#475560" textAnchor="middle" stroke="white" strokeWidth=".065" paintOrder="stroke">{symbol.label}</text>}</g>)}
  {viewpoint && <g transform={`translate(${viewpoint.position.x} ${-viewpoint.position.y}) rotate(${counterRotation}) scale(${symbolFactor})`}><circle r=".16" fill="#2563eb"/><circle r=".26" fill="none" stroke="#2563eb" strokeWidth=".035"/><text y=".57" fontSize=".22" textAnchor="middle" fill="#2563eb" stroke="white" strokeWidth=".06" paintOrder="stroke">U bevindt zich hier</text></g>}
 </>;
 return standalone ? <svg className={className} xmlns="http://www.w3.org/2000/svg" viewBox={`${b.minX} ${-b.maxY} ${b.width} ${b.height}`} role="img" aria-label={`Plattegrond ${floor.name}`} style={{width:'100%',height:'100%',minHeight:200}}>{content}</svg> : <g className={className}>{content}</g>;
}
export { FloorPlanRenderer };
