import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import type { FloorPlanDocument, Floor } from './model';
import FloorPlanRenderer, { defaultLayers, isSymbolVisible, SymbolGlyph } from './FloorPlanRenderer';
import { floorBounds } from './geometry';
import { catalogItem, secondaryCatalogLabel } from './catalog';
export type PrintOptions = { viewpointId?: string; backgroundUrls?:Record<string,string>; revision?:string; logoUrl?: string; pageName?: string };
export function printLayout(floor:Floor, rotation = 0) {
 const sizes = floor.print.paper==='A3'?[297,420]:[210,297]; const [width,height]=floor.print.orientation==='landscape'?[sizes[1],sizes[0]]:sizes;
 const mapWidth = width-24; const symbols=new Set(floor.symbols.filter(s=>isSymbolVisible(s.kind,floor.print.profile,defaultLayers)).map(s=>s.kind)); const legendCount=symbols.size+(floor.routes.length?1:0)+(floor.print.viewpoints.length&&!symbols.has('you_are_here')?1:0); const bilingual=['en','de'].includes(floor.print.language2.toLowerCase().split('-')[0]); const charsPerLine=Math.max(22,Math.floor((mapWidth*.64-55)/1.35)); const textLines=(text:string)=>text.split('\n').reduce((n,line)=>n+Math.max(1,Math.ceil(line.length/charsPerLine)),0); const requestedBottom=Math.max(49,9+Math.ceil(legendCount/2)*(bilingual?8:5.5),9+(textLines(floor.print.instructions)+(floor.print.secondaryInstructions?textLines(floor.print.secondaryInstructions)+1:0))*3.5); const maxBottom=(height-40)*.48; const bottomHeight=Math.min(requestedBottom,maxBottom); const mapHeight=height-56-bottomHeight; const textOverflow=requestedBottom>maxBottom;
 const bounds = floorBounds(floor,floor.print.profile==='installation'); const radians = rotation*Math.PI/180;
 const worldWidth = Math.abs(bounds.width*Math.cos(radians))+Math.abs(bounds.height*Math.sin(radians)); const worldHeight = Math.abs(bounds.height*Math.cos(radians))+Math.abs(bounds.width*Math.sin(radians));
 const crop=floor.print.cropCenter||{x:(bounds.minX+bounds.maxX)/2,y:(bounds.minY+bounds.maxY)/2}; const corners=[{x:bounds.minX,y:bounds.minY},{x:bounds.minX,y:bounds.maxY},{x:bounds.maxX,y:bounds.minY},{x:bounds.maxX,y:bounds.maxY}]; const clipped=corners.some(p=>{const x=(p.x-crop.x)*Math.cos(radians)-(p.y-crop.y)*Math.sin(radians),y=(p.x-crop.x)*Math.sin(radians)+(p.y-crop.y)*Math.cos(radians);return Math.abs(x)*1000/floor.print.scale>mapWidth/2||Math.abs(y)*1000/floor.print.scale>mapHeight/2;}); return {width,height,mapWidth,mapHeight,bottomHeight,textOverflow,bounds,worldWidth,worldHeight,clipped};
}
export function FloorPlanPrint({document,floorId,options={}}:{document:FloorPlanDocument;floorId:string;options?:PrintOptions}) {
 const floor = document.floors.find(f=>f.id===floorId); if(!floor)return null; const logoUrl = options.logoUrl || (floor.print.logoFileId ? options.backgroundUrls?.[floor.print.logoFileId] : undefined);
 const viewpoints=options.viewpointId?floor.print.viewpoints.filter(v=>v.id===options.viewpointId):floor.print.viewpoints.length?floor.print.viewpoints:[undefined];
 return <>{viewpoints.map((viewpoint,index)=>{const layout=printLayout(floor,viewpoint?.rotation||0);const centerX=floor.print.cropCenter?.x??(layout.bounds.minX+layout.bounds.maxX)/2,centerY=floor.print.cropCenter?.y??(layout.bounds.minY+layout.bounds.maxY)/2;const mmPerMetre=1000/floor.print.scale;const kinds=[...new Set(floor.symbols.filter(s=>isSymbolVisible(s.kind,floor.print.profile,defaultLayers)).map(s=>s.kind))];return <article className="plan-sheet" key={index} style={{width:`${layout.width}mm`,height:`${layout.height}mm`,page:options.pageName}}>
 <header><div><span className="eyebrow">LOQ · VEILIGHEID IN BEELD</span><h1>{floor.print.title || document.title}</h1><p>{document.title} · {floor.name}{viewpoint?` · ${viewpoint.label}`:''}</p></div>{logoUrl&&<img alt="Logo" src={logoUrl}/>}</header>
 <div className="drawing-frame" style={{width:`${layout.mapWidth}mm`,height:`${layout.mapHeight}mm`}}><svg xmlns="http://www.w3.org/2000/svg" width={`${layout.mapWidth}mm`} height={`${layout.mapHeight}mm`} viewBox={`0 0 ${layout.mapWidth} ${layout.mapHeight}`}><g transform={`translate(${layout.mapWidth/2} ${layout.mapHeight/2}) scale(${mmPerMetre}) rotate(${-(viewpoint?.rotation||0)}) translate(${-centerX} ${centerY})`}><FloorPlanRenderer floor={floor} standalone={false} profile={floor.print.profile} layers={{background:floor.print.profile==='installation',dimensions:floor.print.profile==='installation'}} dimensions={floor.print.profile==='installation'} backgroundUrls={options.backgroundUrls} viewpoint={viewpoint} printMode printScale={floor.print.scale}/></g></svg>{layout.clipped&&<div className="cropped">Uitsnede · overzicht hieronder</div>}</div>
 <div className="sheet-bottom" style={{height:`${layout.bottomHeight}mm`}}><section className="legend"><h2>Legenda</h2>{kinds.map(kind=><span key={kind}><SymbolGlyph kind={kind} size={18} solid/><span>{catalogItem(kind).label}{secondaryCatalogLabel(kind,floor.print.language2)&&<small>{secondaryCatalogLabel(kind,floor.print.language2)}</small>}</span></span>)}{viewpoint&&!kinds.includes('you_are_here')&&<span><SymbolGlyph kind="you_are_here" size={18} solid/><span>U bevindt zich hier{secondaryCatalogLabel('you_are_here',floor.print.language2)&&<small>{secondaryCatalogLabel('you_are_here',floor.print.language2)}</small>}</span></span>}{floor.routes.length>0&&<span><b style={{color:'#16805b'}}>→</b><span>Vluchtroute{floor.print.language2==='en'?<small>Escape route</small>:floor.print.language2==='de'?<small>Fluchtweg</small>:null}</span></span>}</section><section className="instructions"><h2>Instructies</h2><p>{floor.print.instructions}</p>{floor.print.secondaryInstructions&&<p lang={floor.print.language2||undefined}>{floor.print.secondaryInstructions}</p>}</section><section className="overview"><h2>Overzicht · {floor.name}</h2><FloorPlanRenderer floor={floor} profile={floor.print.profile} dimensions={false} layers={{background:false,labels:false}} viewpoint={viewpoint}/></section></div>
 <footer><span>{floor.print.address || document.title}</span><span>{floor.print.drawingNumber || 'Concept'} · Rev. {options.revision || 'concept'} · {new Date().toLocaleDateString('nl-NL',{timeZone:'Europe/Amsterdam'})}</span><span>{floor.print.paper} · 1:{floor.print.scale} · {index+1}/{viewpoints.length}</span></footer>
 </article>})}</>;
}
const PRINT_CSS = `*{box-sizing:border-box}body{margin:0;color:#283c45;font:9pt -apple-system,BlinkMacSystemFont,Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.plan-sheet{padding:10mm 12mm;overflow:hidden;page-break-after:always;background:#fff}.plan-sheet:last-child{page-break-after:auto}header{height:28mm;display:flex;justify-content:space-between;align-items:flex-start}header img{max-width:35mm;max-height:18mm}.eyebrow{font-size:7pt;font-weight:700;letter-spacing:1.5px;color:#148267}h1{font-size:23pt;line-height:1.15;letter-spacing:-.7px;margin:2mm 0 1mm}header p{margin:0;color:#65717b;font-size:9pt}.drawing-frame{position:relative;border:.25mm solid #e1e5e3;overflow:hidden;border-radius:1.5mm}.cropped{position:absolute;bottom:2mm;right:2mm;font-size:6pt;background:#fff;padding:1mm}.sheet-bottom{display:flex;gap:5mm;height:49mm;padding-top:4mm;overflow:hidden}.sheet-bottom h2{font-size:8pt;text-transform:uppercase;letter-spacing:1px;margin:0 0 2mm}.legend{width:36%;display:flex;align-content:flex-start;gap:1mm 2mm;flex-wrap:wrap}.legend h2{width:100%}.legend>span{display:flex;gap:1.5mm;align-items:center;width:47%;font-size:7.5pt;line-height:1.15}.legend small{display:block;color:#6d7878;font-size:6pt;line-height:1.4;margin-top:.4mm}.legend svg{flex-shrink:0}.instructions{flex:1}.instructions p{white-space:pre-line;margin:0 0 2mm;font-size:7.5pt;line-height:1.5}.overview{width:45mm;flex-shrink:0}.overview>svg{height:34mm!important;min-height:0!important}footer{border-top:.25mm solid #ccd4d0;display:flex;justify-content:space-between;gap:3mm;padding-top:2mm;font-size:6.5pt;color:#6c797a}`;
function documentHtml(markup:string,pageRules:string) {
 return `<!doctype html><html lang="nl"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline';"><title>LOQ Plattegrond</title><style>${pageRules}${PRINT_CSS}</style></head><body>${markup}</body></html>`;
}
function checkedLayout(floor:Floor) {
 if(!Number.isFinite(floor.print.scale)||floor.print.scale<=0)throw new Error('Kies een geldige schaal.');
 const layout=printLayout(floor);
 if(layout.textOverflow)throw new Error(`${floor.name}: de legenda of instructies passen niet leesbaar op dit papierformaat. Kort de instructies in of kies groter papier.`);
 return layout;
}
export function generatePrintHtml(document:FloorPlanDocument,floorId:string,options:PrintOptions={}) {
 const floor=document.floors.find(f=>f.id===floorId);if(!floor)throw new Error('Verdieping niet gevonden.');
 const layout=checkedLayout(floor);
 return documentHtml(renderToStaticMarkup(<FloorPlanPrint document={document} floorId={floorId} options={options}/>),`@page{size:${layout.width}mm ${layout.height}mm;margin:0}`);
}
/** One publication PDF, retaining each floor's physical paper size and every viewpoint. */
export function generateDocumentPrintHtml(document:FloorPlanDocument,options:Omit<PrintOptions,'viewpointId'|'pageName'>={}) {
 if(!document.floors.length)throw new Error('Het gebouw heeft geen verdiepingen.');
 const layouts=document.floors.map(checkedLayout);
 const pageRules=layouts.map((layout,index)=>`@page loq-floor-${index}{size:${layout.width}mm ${layout.height}mm;margin:0}`).join('');
 const content=<>{document.floors.map((floor,index)=><FloorPlanPrint key={floor.id} document={document} floorId={floor.id} options={{...options,pageName:`loq-floor-${index}`}}/>)}</>;
 return documentHtml(renderToStaticMarkup(content),pageRules);
}
export default FloorPlanPrint;
